# analysis_options.yaml

include: package: flutter_lints/flutter.yaml

linter:
  # Mengaktifkan atau menonaktifkan aturan linting tertentu
  rules:
    # Contoh aturan linting
    public_member_api_docs: false
    prefer_final_fields: true
    unnecessary_new: true

analyzer:
  # Mengonfigurasi opsi analisis
  enable-experiment:
    - non-nullable
  errors:
    # Mengatur tingkat kesalahan untuk analisis
    unused_import: error
    missing_required_param: warning
